version: "3.4"

networks:
  dev:
    driver: bridge

services:
  hospital-app:
    image: sawlinthantdocker/hospital-dotnet-api
    depends_on:
      - "patient_database"

    container_name: hospital-api
    ports:
      - "8088:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=postgresql://postgres:sawwinthant@patient_database:5432/hospital_api
      - JWT_SECRET=DhftOS5uphK3vmCJQrexST1RsyjZBjXWRgJMFPU4
      - ALGORITHM=HmacSha256
    networks:
      - dev

  front-end:
    image: sawlinthant/react-patientportal
    container_name: React-JS
    ports:
      - "3000:3000"
    networks:
      - dev

  patient_database:
    image: postgres:latest
    container_name: hospital_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sawwinthant
      - POSTGRES_DB=hospital_api
    restart: always
    volumes:
      - ./db-backups:/docker-entrypoint-initdb.d
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "5050:80"
    depends_on:
      - patient_database
    networks:
      - dev

volumes:
  app_data:
